name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  build_and_deploy_job:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      - name: Publish
        run: |
            dotnet publish src/DungeonDates.Client -o published
      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "published/wwwroot" 
          api_location: "src/DungeonDates.Function"
